PFC.WebApp/Models/Report/SubscriptionStatusResumeDTO.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PFC.WebApp.Models.Report
{
    public class PhoneEventsWithoutSubscriptionDTO
    {
        public string MSISDN { get; set; }

        public int EventsCount { get; set; }

        public DateTime First { get; set; }

        public DateTime Last { get; set; }
    }
}

PFC.WebApp/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.EntityFrameworkCore;
using PFC.WebApp.Data;
using PFC.WebApp.Models.Report;

namespace PFC.WebApp.Controllers
{
    [Authorize(Roles = "SuperAdmin,Gestor")]
    public class ReportController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ReportController(ApplicationDbContext context)
        {
            _context = context;
        }

        public override void OnActionExecuting(ActionExecutingContext context)
        {
            base.OnActionExecuting(context);
            ViewBag.Title = "Informes";
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> PhoneEventsWithoutSubscription()
        {
            var result = await _context.PhoneEvents
                .GroupJoin(_context.Subscriptions,
                    pe => pe.SourceId,
                    s => s.MSISDN,
                    (pe, s) => new
                    {
                        PhoneEvent = pe,
                        Subscription = s.Where(x => pe.Date >= x.SubscriptionDate && (!x.CancellationDate.HasValue || pe.Date < x.CancellationDate.Value.AddDays(1)))
                    })
                    .Where(x => !x.Subscription.Any())
                    .Select(x => x.PhoneEvent)
                    .GroupBy(x => x.SourceId)
                    .Select(x => new PhoneEventsWithoutSubscriptionDTO
                    {
                        MSISDN = x.Key,
                        EventsCount = x.Count(),
                        First = x.Select(pe => pe.Date).Min(),
                        Last = x.Select(pe => pe.Date).Max()
                    })
                    .Distinct()
                    .ToListAsync();

            return View(result);
        }

        public async Task<IActionResult> SubscriptionsWithPendingInvoices()
        {
            var result = await _context.Subscriptions
                .Where(x => x.Invoices.Count < ((x.CancellationDate ?? DateTime.Now).Year - x.SubscriptionDate.Year) * 12 + (x.CancellationDate ?? DateTime.Now).Month - x.SubscriptionDate.Month)
                .Include(x => x.Invoices)
                .ToListAsync();

            return View(result);
        }
    }
}

PFC.WebApp/Controllers/SubscriptionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PFC.WebApp.Data;
using PFC.WebApp.Data.Models;
using PFC.WebApp.Models;
using PFC.WebApp.Models.InvoicesViewModel;
using PFC.WebApp.Support;
using PFC.WebApp.Support.PredicateBuilder;

namespace PFC.WebApp.Controllers
{
    public class SubscriptionsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public SubscriptionsController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public override void OnActionExecuting(ActionExecutingContext context)
        {
            base.OnActionExecuting(context);
            ViewBag.Title = "Abonados";
        }

        // GET: Subscriptions
        public async Task<IActionResult> Index()
        {
            var dataTableDefinition = DataTableDefinition.Create<Subscription>()
                .WithTitle("Abonados")
                .AddGlobalActions("Nuevo", Url.Action(nameof(Create)), "Gestor,SuperAdmin")
                .AddElementAction("Detalles", new DataTableDefinition.UrlActionDTO()
                {
                    Action = "Details",
                    Values = new Dictionary<string, string> { { "id", "ID" } }
                })
                .AddElementAction("Editar", new DataTableDefinition.UrlActionDTO()
                {
                    Action = "Edit",
                    Values = new Dictionary<string, string> { { "id", "ID" } }
                }, "Gestor,SuperAdmin")
                .AddElementAction("Borrar", new DataTableDefinition.UrlActionDTO()
                {
                    Action = "Delete",
                    Values = new Dictionary<string, string> { { "id", "ID" } }
                }, "Gestor,SuperAdmin")
                .MapColumn(nameof(Subscription.UserName), "Usuario", 100)
                .MapColumn(nameof(Subscription.MSISDN), "Número de teléfono", 100)
                .MapColumn(nameof(Subscription.PlanName), "Tarifa", 100)
                .MapColumn(nameof(Subscription.SubscriptionDate), "Fecha de alta", 100)
                .MapColumn(nameof(Subscription.CancellationDate), "Fecha de baja", 100);

            return View(dataTableDefinition);
        }

        [HttpPost]
        public async Task<JsonResult> Index(int index = 0, int length = 10, string orderProperty = null, bool inverse = false, [FromBody]IEnumerable<QueryFilter> query = null)
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);

            DataTableDefinition.DataQuery data =
                DataTableDefinition.DataQueryBuilder(index, length, orderProperty, inverse, query, _context.Subscriptions
                .Include(x => x.User)
                .Include(x => x.Plan)
                .Where(x => User.IsInRole("SuperAdmin") || User.IsInRole("Gestor") || x.UserId == user.Id));

            return base.Json(data, new Newtonsoft.Json.JsonSerializerSettings());
        }

        // GET: Subscriptions/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var subscription = await _context.Subscriptions
                .Include(s => s.Plan)
                .Include(s => s.User)
                .SingleOrDefaultAsync(s => s.ID == id && (User.IsInRole("SuperAdmin") || User.IsInRole("Gestor") || s.User.UserName == User.Identity.Name));

            if (subscription == null)
                return NotFound();

            ViewBag.InvoiceDataTableDefinition = DataTableDefinition.Create<Invoice>()
                .WithTitle("Facturas")
                .AddGlobalActions("Nuevo", Url.Action(nameof(Invoice), new { id }), "Gestor,SuperAdmin")
                .AddElementAction("Detalles", new DataTableDefinition.UrlActionDTO()
                {
                    Action = "Details",
                    Controller = "Invoices",
                    Values = new Dictionary<string, string> { { "id", "ID" } }
                })
                .MapColumn(nameof(Data.Models.Invoice.Identificador), "Factura", 100)
                .MapColumn(nameof(Data.Models.Invoice.YearPeriod), "Año", 100)
                .MapColumn(nameof(Data.Models.Invoice.MonthPeriod), "Mes", 100)
                .MapColumn(nameof(Data.Models.Invoice.StateString), "Estado", 100)
                .MapColumn(nameof(Data.Models.Invoice.Total), "Total", 100);

            return View(subscription);
        }

        // GET: Subscriptions/Details/5
        [HttpPost]
        public async Task<IActionResult> Details(int id, int index = 0, int length = 10, string orderProperty = null, bool inverse = false, [FromBody]IEnumerable<QueryFilter> query = null)
        {
            IQueryable<Invoice> invoices = _context.Invoice;

            if (orderProperty == null)
                invoices = invoices.OrderByDescending(x => x.StartDate);

            DataTableDefinition.DataQuery data =
                DataTableDefinition.DataQueryBuilder(index, length, orderProperty, inverse, query, invoices.Where(x => x.SubscriptionId == id));

            return base.Json(data, new Newtonsoft.Json.JsonSerializerSettings());
        }

        // GET: Subscriptions/Create
        [Authorize(Roles = "Gestor,SuperAdmin")]
        public IActionResult Create()
        {
            ViewData["PlanId"] = new SelectList(_context.Plan, nameof(Plan.ID), nameof(Plan.Name));
            return View();
        }

        // POST: Subscriptions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Gestor,SuperAdmin")]
        public async Task<IActionResult> Create([Bind("ID,MSISDN,PlanId,SubscriptionDate,CancellationDate,UserId")] Subscription subscription)
        {
            //#error Validad fechas
            ValidateModel(subscription);

            ViewData["PlanId"] = new SelectList(_context.Plan, nameof(Plan.ID), nameof(Plan.Name));
            if (!ModelState.IsValid)
                return View(subscription);

            _context.Add(subscription);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Subscriptions/Edit/5
        [Authorize(Roles = "Gestor,SuperAdmin")]
        public async Task<IActionResult> Edit(int id)
        {
            var subscription = await _context.Subscriptions
                .Include(x => x.User)
                .SingleOrDefaultAsync(m => m.ID == id);

            if (subscription == null)
                return NotFound();

            ViewData["PlanId"] = new SelectList(_context.Plan, nameof(Plan.ID), nameof(Plan.Name));

            if (nonEditableSubscription(subscription))
                this.DisallowFormEdition("Existe algun abonado con fecha de alta posterior al actual");

            return View(subscription);
        }

        // POST: Subscriptions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Gestor,SuperAdmin")]
        public async Task<IActionResult> Edit([Bind("ID,UserId,MSISDN,PlanId,SubscriptionDate,CancellationDate")] Subscription subscription)
        {
            if (!_context.Subscriptions.Any(x => x.ID == subscription.ID))
                return NotFound();

            ValidateModel(subscription);

            // intento de edición del formulario no autorizado, debería haberse deshabilitado en el get
            if (ModelState.IsValid && nonEditableSubscription(subscription))
                return Unauthorized();


            ViewData["PlanId"] = new SelectList(_context.Plan, nameof(Plan.ID), nameof(Plan.Name));
            if (!ModelState.IsValid)
                return View(subscription);

            var entry = _context.Update(subscription);

            // Ignoramos la actualización del usuario
            entry.Property(x => x.UserId).IsModified = false;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool nonEditableSubscription(Subscription subscription)
        {
            return _context.Subscriptions.Any(x => x.MSISDN == subscription.MSISDN && x.SubscriptionDate > subscription.CancellationDate);
        }

        private void ValidateModel(Subscription subscription)
        {
            // Validación del rango de fechas de alta del abonado
            if (subscription.CancellationDate < subscription.SubscriptionDate)
                ModelState.AddModelError(nameof(Subscription.CancellationDate), "La fecha de baja no puede ser menor a la fecha de alta");

            var otherSubscriptions = _context.Subscriptions
                .Where(x => x.MSISDN == subscription.MSISDN && x.ID != subscription.ID);

            Subscription lastActiveSubscription = otherSubscriptions.Where(x => !x.CancellationDate.HasValue || x.CancellationDate >= subscription.SubscriptionDate).LastOrDefault();
            if (lastActiveSubscription != null)
            {
                if (lastActiveSubscription.CancellationDate.HasValue)
                    ModelState.AddModelError(nameof(Subscription.SubscriptionDate), $"La fecha de alta del abonado debe ser mayor que {lastActiveSubscription.CancellationDate.Value.ToShortDateString()}");

PFC.WebApp/Views/Report/Index.cshtml
@{
    ViewBag.Subtitle = "Listado";
}

<ul>
    <li>
        <a href="@Url.Action(nameof(PFC.WebApp.Controllers.ReportController.PhoneEventsWithoutSubscription))">Eventos telefónicos sin abonado vigente</a>
    </li>
    <li>
        <a href="@Url.Action(nameof(PFC.WebApp.Controllers.ReportController.SubscriptionsWithPendingInvoices))">Abonados telefónicos con facturas pendientes de emisión</a>
    </li>
</ul>

PFC.WebApp/Views/Report/PhoneEventsWithoutSubscription.cshtml
@model IEnumerable<PFC.WebApp.Models.Report.PhoneEventsWithoutSubscriptionDTO>

@{ 
    ViewBag.Subtitle = "Eventos telefónicos sin abonado vigente";
    ViewBag.ReturnUrl = Url.Action(nameof(PFC.WebApp.Controllers.SubscriptionsController.Index));
}

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MSISDN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventsCount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Last)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MSISDN)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EventsCount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.First)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Last)
                </td>
            </tr>
        }
    </tbody>
</table>

PFC.WebApp/Views/Report/SubscriptionsWithPendingInvoices.cshtml
@model IEnumerable<PFC.WebApp.Data.Models.Subscription>

@{
    ViewBag.Subtitle = "Abonados telefónicos con facturas pendientes de emisión";
    ViewBag.ReturnUrl = Url.Action(nameof(PFC.WebApp.Controllers.SubscriptionsController.Index));
}

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MSISDN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SubscriptionDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CancellationDate)
            </th>
            <th>Facturas emitidas</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MSISDN)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SubscriptionDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CancellationDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Invoices.Count)
                </td>
                <td>
                    <a href="@Url.Action(nameof(PFC.WebApp.Controllers.SubscriptionsController.Details),"Subscriptions", new { id = item.ID})"><i class="glyphicon glyphicon-eye-open"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>